services:
  - type: web
    name: tesis-1-pq9m
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -B -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGINS
        value: https://exquisite-blini-d76e47.netlify.app,http://localhost:55912,http://127.0.0.1:55912
      - key: PYTHON_VERSION
        value: "3.12"
